---
title: "UHA_Analysis_nomd_ME"
author: "Mikaely Evans"
date: "2023-07-14"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
library(PolyPatEx)
library(readr)
library(gtools)
library(dplyr)
library(tidyr)
library(tidyverse)
library(naniar)
```

```{r}
setwd("C:/Users/MEvans/Documents/UHA_Analysis")
system.file("extdata", package = "PolyPatEx")
# fixCSV("UHA_Final_Scores_nomd_df_PolyPatEx.csv", overwrite=TRUE)
UHA_final_scores <- inputData("UHA_Final_Scores_nomd_df_PolyPatEx.csv",
                              numLoci = 14,
                              ploidy = 2,
                              dataType = "genotype",
                              dioecious = FALSE,
                              selfCompatible = FALSE,
                              lociMin = 10,
                              matMismatches = 1)

UHA_final_scores[UHA_final_scores == 0] <- NA

ppe1 <- genotPPE(UHA_final_scores)
write.csv(potentialFatherCounts(ppe1),file="pFatherCounts.csv")
write.csv(potentialFatherIDs(ppe1),file="pFatherIDs.csv")
```

