---
title: "UHA_Evans_Final_Figures_Parentage_Results"
author: "Mikaely Evans"
date: "2023-07-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load the necessary packages to run code below and load the results from the parentage analysis generated by CERVUS (here)[https://github.com/botanic-ash/USBGHybridAcornsREU2023/tree/main/Paternity_Analysis/UHA_nomd_CERVUS_Analysis]
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(geofi)
library(sf)
library(geosphere)

wd <- getwd()

spatial_parentage_results <- read.csv(paste0(wd,"/../../Data_Files/Clean_Data_Files/Clean_csv/UHA_full_parentage.csv")) %>%
  rename(Mother_ID = Mother.ID, 
         Father_ID = Candidate.father.ID, ) %>%
  filter(!is.na(Father_ID))
```


Generate a barchart of the assignments of progeny to both mother and father
```{r}
spatial_parentage_results %>%
  ggplot() +
  geom_bar(aes(y=Father_ID), fill="darkslategrey") +  # bar graph to show offspring by father
    theme_bw() +
  facet_wrap(~Mother_ID, ncol = 4) +  # Separates graph by maternal tree
  labs(y = "Proposed Father ID",
       x = "Offspring Count",
       title = "Maternal Tree Focused Sibling Analysis")
  
```

Get the distances between each proposed parent using the geosphere functions distm and distGeo
```{r}
#create a column for distance between mom and dad 
spatial_parentage_results$distance_between_parents <- NA

#loop to calculate distance between parents
for(d in 1:nrow(spatial_parentage_results)){
  mom_long_lat <- c(spatial_parentage_results[d,]$Maternal.Longitude, spatial_parentage_results[d,]$Maternal.Latitude)
  dad_long_lat <- c(spatial_parentage_results[d,]$Candidate.Father.Longitude, spatial_parentage_results[d,]$Candidate.Father.Latitude)
  
  spatial_parentage_results$distance_between_parents[d] <- distGeo(mom_long_lat,dad_long_lat) 

}

#calculate mean distance between parents 
UHA_dist_matrix <- matrix(nrow = length(unique(spatial_parentage_results$Mother_ID)),
                          ncol = 1)
for(m in 1:length(unique(spatial_parentage_results$Mother_ID))){

  UHA_dist_matrix[m,1] <- mean(spatial_parentage_results[spatial_parentage_results$Mother_ID == unique(spatial_parentage_results$Mother_ID)[[m]],][,15])

}

#name matrix 
rownames(UHA_dist_matrix) <- unique(spatial_parentage_results$Mother_ID)
colnames(UHA_dist_matrix) <- "Mean_Dist_Parents"

##plot different distances between parents 
pdf("dist_parents.pdf", width = 8, height = 8)
boxplot(spatial_parentage_results$distance_between_parents~spatial_parentage_results$Mother_ID,
        ylim = c(0,600), xlab = "Maternal Individual",
        ylab = "Distance between Parents")


# Mikaely Evans code for creating a new column to assign half sibling status to all the offspring
spatial_parentage_results$half_sibs <- NA  # Made three new columns for this analysis
spatial_parentage_results$M_Accession_Abrv <- NA  
spatial_parentage_results$F_Accession_Abrv <- NA
# Abbreviating the accession numbers for the maternal and paternal trees was necessary to assign half sibling status because it is only necessary to look at the first 6 characters in the accession number to know if the trees came from the same lineage.

spatial_parentage_results$M_Accession_Abrv <- substr(spatial_parentage_results$Mother_Accession, 0, 6)
# This line adds the Maternal accession abbreviation to the M_Accession_Abrv column

spatial_parentage_results$F_Accession_Abrv <- substr(spatial_parentage_results$Candidate_Father_Accesion, 0, 6)
# This line adds the paternal accession abbreviation to the F_Accession_Abrv column

spatial_parentage_results <- spatial_parentage_results %>%
  mutate('Half Siblings' = case_when(M_Accession_Abrv == F_Accession_Abrv ~ "Mating with half siblings",
                               M_Accession_Abrv != F_Accession_Abrv ~ "Not mating with half siblings"))
# This chunk above uses mutate to change the 'Half Siblings' column to represent the cases when the maternal accession and paternal accession match, and when they don't. They are represented by short phrases that are easier for readers to understand when they are graphed below.

```

```{r}
spatial_parentage_results %>%
  group_by(Mother_ID)  # Grouped by mother ID for analysis across maternal tree
  ggplot(data = spatial_parentage_results, aes(x = Mother_ID, y = distance_between_parents)) +
    expand_limits(y = c(0, 600)) +  # set limits for graph
    theme_minimal() +  # set theme
    theme_bw() +  # set theme
  geom_boxplot(fill="darkolivegreen4") +
  labs(title = "Distance between parents grouped by Maternal Tree",
       y = "Distance between parents (m)", x = "Maternal Tree ID")  # add labels
```


```{r}
spatial_parentage_results %>%
  group_by(`Half Siblings`)  # group by half siblings to compare the status
  ggplot(data = spatial_parentage_results, aes(x = Mother_ID, y = distance_between_parents,  fill=`Half Siblings`, col = `Half Siblings`)) +  # color and fill by half siblings so you can see the maternal trees who did and didn't mate with half siblings
    expand_limits(y = c(0, 600)) +  # set limits for graph
    theme_bw() +
  geom_boxplot() +
    scale_fill_brewer(palette="Dark2") +
    scale_color_brewer(palette = "Dark2") +   # Set colors
  labs(title = "Distance between parents grouped by half siblings",
       y = "Distance between parents (m)", x = "Maternal Tree ID")  # set labels
```



